language: java
jdk:
  - openjdk8

branches:
  only:
    - master

env:
  global:
    - secure: nNXM08YMAgDXc8RgJ3/nzV271NJKu0rFoSW6yLquQBO/6nVtazPmEXiIGkoQWwNtFudxC4Sy90LzXkP+mY+YKjcsSxgiYK1xWTtE/ET1H/mdsGAYz1NLlpl2mYx9rBHbOcGD1FWRBqpz+kEApqadFnR2GULEp2AMLfppsXairfuef403+thgfMmGbtrYH94ZGf5ftwLipzdwI8gKRgFB4WScK1y4lUfYYY6RanB4vDsYhTYRlkobHGsN2KFktemOQT67vF1v3QtJVnvRppwdaK4gC7OmelKicZD17wjDIx9NHBoEIiPhtEWndM21JULsaImQO1lagEL1iIs/Yiiut1FLKodoIsH+LpDhEk7sJBac8x+56W4nk/aRTzHHwg8aFwTz7vb9jv1maO8CNxU4SSK9wvUyvCVZF8GrLh3Bl/i1TtGdSLcMmBMMhop/D2B/wdP1kK0T15nSkqIDufFjs1Ql30CHxIRO1BmrCEJKFfp+bbFO47EU6G19uvd6AYr1zR+WouXNEsmZ4gZ1ZAbwCRweqqhmip81ZuHy/+0E62b87JdN/gT7n5DdG8pZLg6joHpbSIyAO2O7UdbbdWcJHepLMy5mqQM3xoxn4c/Jkee+RQLDW4bAsYMNduhlFHRFqeuhEYRnBChfrG17p6cCRpJ7ctReU0izaShho4EN8Xw=
    - secure: f/wkSyy2xQKt/uL8cg59kHVymtbBLMslk9SRFAlvt9wLwOqn8nf+g5MfwtWDDscLmE9at7MUxnFJ2IlhJYiB8Pu8Qtg9kR1D3ZRlj+pvuDexxaYrhYxjgr9pVmOt05db2FNhbN++DrImu1YP/9yqtAjkmnXxDwaDwuAXHVEzM5NAkKbDEJX+6lNnaUpIKDrUC+uoo5Y+G/b4Fvch5Cf/rmayUlfoNuNo/sxd1mBu3I9vBdH/bfx+bUZ3YcWEpXyGeFGmJK/ZoZOxel1LxPVm0M20pEj/75KDDCVvLeay26/CE8kRAn4/BIKBtYQtjH/VWaHivenBcM/8M3TqHDCdF3GOb/DsILRajaJ1Bq1O6COOin2c0Pu1CoQMXnSiIpVZz44G3QNu84F1KeiQrnK/j8pdMjbdV202/FE+k0118KYXlayZ6ohEkIc85HjYT6iYvo2FTy8Z4dJuZoAtvoXmeWf0SwHfGLJKeNaZrjmK2y8246xpXUzEp16uSUpt5mIdImh0Wlgazy90Zt9q1sJ3Pml7sLWL5OjmeeVAZh1QQ1M5YnNbfQgmij/3pyWlFR+/GFFh0ymzbY+bt9gjrI1ruZ3cq1vZ8xgyl0j7RqzmDEyMH3kxHHz1S1/3/rVC8o4UtPqlkBpnAmEJb58a+C6k9e5Z6pAhJB6s0GkzCKZNghM=

deploy:
  - provider: script
    script: bash docker-deploy.sh
    skip_cleanup: true
    on:
      repo: WoowaCrew/WoowaCrewCI
      branch: master

notifications:
  email:
    recipients:
      - hyojaedev@gmail.com
