spring:
  profiles: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woowacrew?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: woowacrew

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
